'use client'
import { sendEmailVerification,sendPasswordResetEmail,signInWithEmailAndPassword,signOut,type User } from 'firebase/auth'
import { useEffect,useState } from 'react'
import { useRouter } from 'next/navigation'
import { getFirebaseClient } from '@/lib/firebase/client'
import { Button,Field,Header,PageTitle,Shell } from '@/components/shared/ui'

type SessionResult={state:'ACTIVE_WORKSPACE'|'ONBOARDING_REQUIRED';requestId?:string}
async function exchange(user:User):Promise<SessionResult>{const csrfResponse=await fetch('/api/auth/session'),csrfBody=await csrfResponse.json(),response=await fetch('/api/auth/session',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({idToken:await user.getIdToken(true),csrfToken:csrfBody.data.csrfToken})}),body=await response.json();if(!response.ok){const error=new Error(body.error?.message??'Could not create a secure session.') as Error&{code?:string;requestId?:string};error.code=body.error?.code;error.requestId=body.requestId;throw error}return{...body.data,requestId:body.requestId}}

export function FirebaseOwnerLogin(){const router=useRouter(),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[verificationUser,setVerificationUser]=useState<User>(),[cooldown,setCooldown]=useState(0)
 useEffect(()=>{if(cooldown<=0)return;const timer=setInterval(()=>setCooldown(value=>Math.max(0,value-1)),1000);return()=>clearInterval(timer)},[cooldown])
 const route=(result:SessionResult)=>{router.replace(result.state==='ONBOARDING_REQUIRED'?'/owner/onboarding':'/owner/dashboard');router.refresh()}
 const login=async()=>{setBusy(true);setMessage('');try{const credential=await signInWithEmailAndPassword(getFirebaseClient().auth,email,password);try{route(await exchange(credential.user))}catch(reason){const error=reason as Error&{code?:string;requestId?:string};if(error.code==='EMAIL_VERIFICATION_REQUIRED'){setVerificationUser(credential.user);setMessage('Verify your email to continue.');return}throw error}}catch(reason){const error=reason as Error&{code?:string;requestId?:string};if(error.code==='FORBIDDEN'||error.code==='TENANT_SUSPENDED')setMessage(error.message);else setMessage(error.requestId?`Sign-in could not be completed. Request ID: ${error.requestId}`:'Sign-in failed. Check your credentials and try again.')}finally{setBusy(false)}}
 const resend=async()=>{if(!verificationUser||cooldown)return;setBusy(true);try{await sendEmailVerification(verificationUser);setCooldown(60);setMessage('Verification email sent. Check your inbox.')}catch{setMessage('Could not resend the verification email. Try again shortly.')}finally{setBusy(false)}}
 const checkAgain=async()=>{if(!verificationUser)return;setBusy(true);try{await verificationUser.reload();route(await exchange(verificationUser))}catch(reason){const error=reason as Error&{code?:string;requestId?:string};setMessage(error.code==='EMAIL_VERIFICATION_REQUIRED'?'Your email is not verified yet. Open the link, then check again.':`Could not refresh your account.${error.requestId?` Request ID: ${error.requestId}`:''}`)}finally{setBusy(false)}}
 const leave=async()=>{await signOut(getFirebaseClient().auth);await fetch('/api/auth/session',{method:'DELETE'}).catch(()=>undefined);setVerificationUser(undefined);setPassword('');setMessage('Signed out.')}
 const reset=async()=>{if(!email)return setMessage('Enter your email first.');try{await sendPasswordResetEmail(getFirebaseClient().auth,email)}catch{}setMessage('If that account exists, password reset instructions have been sent.')}
 return <Shell><section className="flex min-h-dvh flex-col px-5 py-8"><Header title="Owner Console" subtitle="TurfMate"/>{verificationUser?<div className="mt-12"><PageTitle eyebrow="Account security" title="Verify your email to continue." detail="Open the verification link sent by Firebase, then return here."/><div className="mt-8 space-y-3">{message&&<p className="text-sm text-muted-foreground" role="status">{message}</p>}<Button disabled={busy||cooldown>0} onClick={resend} className="w-full">{cooldown?`Resend available in ${cooldown}s`:'Resend verification email'}</Button><Button disabled={busy} variant="secondary" onClick={checkAgain} className="w-full">I have verified — check again</Button><Button disabled={busy} variant="ghost" onClick={leave} className="w-full">Sign out</Button></div></div>:<><div className="mt-12"><PageTitle eyebrow="Welcome back" title="Run your turf." detail="Sign in to your secure workspace."/></div><div className="mt-8 space-y-4"><Field label="Email" type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)}/><Field label="Password" type="password" autoComplete="current-password" value={password} onChange={event=>setPassword(event.target.value)}/>{message&&<p className="text-sm text-muted-foreground" role="status">{message}</p>}<Button disabled={busy} onClick={login} className="w-full">{busy?'Loading session…':'Sign in'}</Button><button onClick={reset} className="w-full py-2 text-sm font-semibold text-primary">Forgot password?</button></div></>}</section></Shell>}
