import 'server-only'
import { FieldValue } from 'firebase-admin/firestore'
import { z } from 'zod'
import { adminDb } from '@/lib/firebase/admin'
import { DomainError } from '@/lib/domain/errors'
import { phoneSchema,slugSchema } from '@/lib/domain/schemas'

const reserved=new Set(['api','owner','admin','login','booked'])
export const onboardingSchema=z.object({name:z.string().trim().min(2).max(100),slug:slugSchema,address:z.string().trim().min(3).max(300),locality:z.string().trim().min(2).max(100),phone:phoneSchema,timezone:z.string().trim().min(3).max(100).default('Asia/Kolkata')}).strict()
export const normalizeOnboardingSlug=(value:string)=>slugSchema.parse(value.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))

export async function slugAvailable(slugInput:string){const slug=normalizeOnboardingSlug(slugInput);if(reserved.has(slug))return{slug,available:false};return{slug,available:!(await adminDb().doc(`publicTurfs/${slug}`).get()).exists}}

export async function createWorkspace(uid:string,email:string,input:z.infer<typeof onboardingSchema>,requestId:string){const value={...input,slug:normalizeOnboardingSlug(input.slug)};if(reserved.has(value.slug))throw new DomainError('VALIDATION_ERROR','Choose a different public URL.',409);const db=adminDb(),tenantId=`tenant_${uid}`,turfId='main',now=FieldValue.serverTimestamp();return db.runTransaction(async tx=>{const userRef=db.doc(`users/${uid}`),tenantRef=db.doc(`tenants/${tenantId}`),memberRef=db.doc(`tenants/${tenantId}/members/${uid}`),publicRef=db.doc(`publicTurfs/${value.slug}`);const [user,tenant,publicSlug]=await Promise.all([tx.get(userRef),tx.get(tenantRef),tx.get(publicRef)]);const existingTenant=(user.data()?.onboardingTenantId as string|undefined)??(tenant.exists?tenantId:undefined);if(existingTenant){const existing=await tx.get(db.doc(`tenants/${existingTenant}`));if(existing.exists)return{tenantId:existingTenant,slug:String(existing.data()?.slug),created:false}}if(publicSlug.exists&&publicSlug.data()?.tenantId!==tenantId)throw new DomainError('VALIDATION_ERROR','That public URL is already in use.',409);const publicTurf={tenantId,turfId,slug:value.slug,name:value.name,shortName:value.name,address:value.address,locality:value.locality,mapUrl:'',phone:value.phone,whatsapp:value.phone,sports:['Football'],amenities:[],timezone:value.timezone,branding:{primary:'#171717'},isBookingEnabled:true};tx.create(tenantRef,{id:tenantId,slug:value.slug,legalName:value.name,displayName:value.name,primaryTurfId:turfId,status:'ACTIVE',timezone:value.timezone,createdAt:now,updatedAt:now});tx.create(memberRef,{uid,tenantId,role:'OWNER',permissions:[],status:'ACTIVE',email,createdAt:now,updatedAt:now});tx.set(userRef,{uid,email,tenantIds:FieldValue.arrayUnion(tenantId),onboardingTenantId:tenantId,updatedAt:now},{merge:true});tx.create(db.doc(`tenants/${tenantId}/turfs/${turfId}`),{...publicTurf,id:turfId,createdAt:now,updatedAt:now});tx.create(publicRef,publicTurf);for(let weekday=0;weekday<7;weekday++)tx.create(db.doc(`tenants/${tenantId}/operatingHours/${weekday}`),{weekday,closed:false,openMinute:360,closeMinute:1320,updatedAt:now});tx.create(db.doc(`tenants/${tenantId}/pricingRules/base`),{id:'base',tenantId,turfId,days:[0,1,2,3,4,5,6],startTime:0,endTime:1440,hourlyRate:1200,currency:'INR',priority:1,createdAt:now,updatedAt:now});tx.create(db.doc(`tenants/${tenantId}/settings/booking`),{paymentMode:'PERCENTAGE',paymentCollectionMode:'CASHFREE',advanceValue:50,minDurationMinutes:60,maxDurationMinutes:180,slotIntervalMinutes:30,cancellationEnabled:true,cancellationCutoffHours:4,bookingWindowDays:60,holdDurationMinutes:10,manualPriceOverrideEnabled:true,updatedAt:now});tx.create(db.collection(`tenants/${tenantId}/auditLogs`).doc(),{tenantId,actorType:'USER',actorId:uid,action:'WORKSPACE_CREATED',entityType:'TENANT',entityId:tenantId,requestId,createdAt:now});return{tenantId,slug:value.slug,created:true}})}
