import 'server-only'
import { cookies } from 'next/headers'
import { adminAuth,adminDb } from '@/lib/firebase/admin'
import { DomainError } from '@/lib/domain/errors'
import { hasPermission } from './permissions'
import type { Permission,Role,TenantMember } from '@/lib/domain/backend-types'

export const sessionCookieName=()=>process.env.SESSION_COOKIE_NAME??'turfmate_session'
const verificationRequired=()=>process.env.APP_ENV==='production'||process.env.OWNER_EMAIL_VERIFICATION_REQUIRED!=='false'
const selfServiceEnabled=()=>process.env.ALLOW_SELF_SERVICE_ONBOARDING==='true'
export async function createOwnerSession(idToken:string){const decoded=await adminAuth().verifyIdToken(idToken,true);if(verificationRequired()&&!decoded.email_verified)throw new DomainError('EMAIL_VERIFICATION_REQUIRED','Verify your email to continue.',403);const user=await adminDb().doc(`users/${decoded.uid}`).get();const tenantIds=(user.data()?.tenantIds??[]) as string[];for(const tenantId of tenantIds){const member=await adminDb().doc(`tenants/${tenantId}/members/${decoded.uid}`).get();if(member.exists&&member.data()?.status==='ACTIVE'){const maxAge=Number(process.env.SESSION_COOKIE_MAX_AGE??432000);return{cookie:await adminAuth().createSessionCookie(idToken,{expiresIn:maxAge*1000}),maxAge,uid:decoded.uid,tenantId,state:'ACTIVE_WORKSPACE' as const}}}if(tenantIds.length>0||!selfServiceEnabled())throw new DomainError('FORBIDDEN','Your account requires a TurfMate invitation.',403);const maxAge=Number(process.env.SESSION_COOKIE_MAX_AGE??432000);return{cookie:await adminAuth().createSessionCookie(idToken,{expiresIn:maxAge*1000}),maxAge,uid:decoded.uid,state:'ONBOARDING_REQUIRED' as const}}
export async function requireSessionIdentity(){const value=(await cookies()).get(sessionCookieName())?.value;if(!value)throw new DomainError('UNAUTHENTICATED','Sign in to continue.',401);try{const decoded=await adminAuth().verifySessionCookie(value,true);if(verificationRequired()&&!decoded.email_verified)throw new DomainError('EMAIL_VERIFICATION_REQUIRED','Verify your email to continue.',403);return decoded}catch(error){if(error instanceof DomainError)throw error;throw new DomainError('UNAUTHENTICATED','Your session has expired. Sign in again.',401)}}
export async function requireOnboardingSession(){if(!selfServiceEnabled())throw new DomainError('FORBIDDEN','Your account requires a TurfMate invitation.',403);const decoded=await requireSessionIdentity(),user=await adminDb().doc(`users/${decoded.uid}`).get(),tenantIds=(user.data()?.tenantIds??[]) as string[],completed=user.data()?.onboardingTenantId as string|undefined;for(const tenantId of tenantIds){const member=await adminDb().doc(`tenants/${tenantId}/members/${decoded.uid}`).get();if(member.exists&&member.data()?.status==='ACTIVE'){if(completed===tenantId)return{uid:decoded.uid,email:decoded.email??''};throw new DomainError('FORBIDDEN','This account already has an active workspace.',403)}}if(tenantIds.length)throw new DomainError('TENANT_SUSPENDED','Workspace access is suspended.',403);return{uid:decoded.uid,email:decoded.email??''}}
export async function requireOwner(permission?:Permission){const value=(await cookies()).get(sessionCookieName())?.value;if(!value)throw new DomainError('UNAUTHENTICATED','Sign in to continue.',401);let decoded;try{decoded=await adminAuth().verifySessionCookie(value,true)}catch{throw new DomainError('UNAUTHENTICATED','Your session has expired. Sign in again.',401)}const user=await adminDb().doc(`users/${decoded.uid}`).get();const activeTenantId=(await cookies()).get('turfmate_active_tenant')?.value;const tenantIds=(user.data()?.tenantIds??[]) as string[];const tenantId=activeTenantId&&tenantIds.includes(activeTenantId)?activeTenantId:tenantIds[0];if(!tenantId)throw new DomainError('FORBIDDEN','No workspace membership was found.',403);const snap=await adminDb().doc(`tenants/${tenantId}/members/${decoded.uid}`).get();if(!snap.exists||snap.data()?.status!=='ACTIVE')throw new DomainError('TENANT_SUSPENDED','Workspace access is suspended.',403);const member={...snap.data(),uid:decoded.uid,tenantId} as TenantMember;if(permission&&!hasPermission(member.role as Role,permission,member.permissions))throw new DomainError('FORBIDDEN','You do not have permission for this action.',403);return{uid:decoded.uid,tenantId,member}}
